test:
  url: ${TEST_URL:http://localhost:4075}
  user-service-url: ${OPAL_USER_SERVICE_API_URL:http://localhost:4555}
  db:
    url: ${FUNCTIONAL_TEST_DB_URL:}
    username: ${FUNCTIONAL_TEST_DB_USERNAME:}
    password: ${FUNCTIONAL_TEST_DB_PASSWORD:}
  sftp:
    host: ${FUNCTIONAL_TEST_SFTP_HOST:}
    port: ${FUNCTIONAL_TEST_SFTP_PORT:22}
    username: ${FUNCTIONAL_TEST_SFTP_USERNAME:}
    password: ${FUNCTIONAL_TEST_SFTP_PASSWORD:}
