include:
  - path: ../opal-shared-infrastructure/docker-compose.yml

services:
  opal-file-handling:
    env_file:
      - ../opal-shared-infrastructure/docker-files/.env.shared
    environment:
      # these environment variables are used by java-logging library
      - ROOT_APPENDER
      - JSON_CONSOLE_PRETTY_PRINT
      - ROOT_LOGGING_LEVEL
      - REFORM_SERVICE_TYPE
      - REFORM_SERVICE_NAME
      - REFORM_TEAM
      - REFORM_ENVIRONMENT
      - LOGBACK_DATE_FORMAT
      - LOGBACK_REQUIRE_THREAD
      - LOGBACK_REQUIRE_ALERT_LEVEL=false
      - LOGBACK_REQUIRE_ERROR_CODE=false
      - OPAL_FILE_HANDLING_DB_HOST=opal-file-handling-db
      - OPAL_FILE_HANDLING_DB_USERNAME=opal-db-user
      - OPAL_FILE_HANDLING_DB_PASSWORD=opal-db-password
      - OPAL_USER_SERVICE_API_URL=http://host.docker.internal:4555/
      - TESTING_SUPPORT_ENDPOINTS_ENABLED=true
      - LAUNCH_DARKLY_ENABLED=true
    ports:
      - "${FINES_PORT:-4075}:4075"
    depends_on:
      - opal-db
      - redis
    networks:
      - default
