services:
  opal-file-handler-service:
    image: file-handler-service:local
    build:
      context: ../opal-file-handler-service
      args:
        - http_proxy
        - https_proxy
        - no_proxy