java:
  applicationPort: 4075
  image: 'hmctspublic.azurecr.io/opal/filehandling:latest'
  ingressHost: opal-filehandling-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: opal
#  Uncomment once the vault containing the app insights key has been set up
#  keyVaults:
#    opal:
#      secrets:
#        - name: AppInsightsInstrumentationKey
#          alias: azure.application-insights.instrumentation-key
  environment:
